spring:
  application:
    name: mcp-server-ciku
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/message